cache:
  directories:
  - $HOME/.m2
matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    language: java
    jdk: oraclejdk8
  - os: osx
    language: java
    osx_image: xcode9.2
addons:
  apt:
    packages:
      - mingw-w64
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
install: true
script:
  - mvn -B package -Dgpg.skip=true
